{ config, ... }:
{
  # Wireguard interfaces
  networking.wg-quick.interfaces.wg0 = {
    # Whether to bring up this interface automatically during boot
    autostart = true;

    # The IP addresses of the interface
    address = [ "10.2.0.2/32" ];

    # Private key file as generated by wg genkey
    privateKeyFile = config.sops.secrets."networking/wg-quick/interfaces/wg0/privateKeyFile".path;

    # The IP addresses of DNS servers to configure
    dns = [ "10.2.0.1" ];

    # Peers linked to the interface
    peers = [
      {
        # The base64 public key to the peer
        publicKey = "+kfPCjoNEateo3jVc9tcduKh6nwQpoKx0/JXxgjHD2c=";

        # List of IP (v4 or v6) addresses with CIDR masks from which this peer is allowed to send incoming traffic and to which outgoing traffic for this peer is directed
        allowedIPs = [ "0.0.0.0/0" ];

        # Endpoint IP or hostname of the peer, followed by a colon, and then a port number of the peer
        endpoint = "190.2.147.7:51820";
      }
    ];
  };

  # Specify encrypted sops secret to access
  sops.secrets."networking/wg-quick/interfaces/wg0/privateKeyFile" = {
    sopsFile = ../../secrets.yaml;
  };
}
